---
title: "Primary Endpoint Analyses "
author: "Laura Klinkhamer"
date: "2023-01-16"
output:
    rmdformats::readthedown:
      toc_depth: 4
---

```{r setup, include=TRUE, message = FALSE, , warning = FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "<path>")

library(readr)
library(tidyverse)
library(ggplot2)
library(kableExtra)
library(ggmosaic)
library(RColorBrewer)
```

### Loading the data

```{r include=TRUE, message = FALSE, warning = TRUE}
setwd('<path>')

basic_information <- read_tsv('basic_information.tsv')
BPI <- read_tsv('BPI.tsv')

```


### Primary outcome analysis

```{r include=TRUE, message = FALSE, warning = TRUE}

# Data ordered and proportion of differences test run to match the output of the ECTU statisician's report exactly

responder_table <- basic_information %>% 
  group_by(AllocatedTreatment) %>%
  count(Improver_status_week6) %>%
  pivot_wider(names_from = Improver_status_week6, values_from = n) %>%
  select(AllocatedTreatment,  'Improver', 'Non-improver') %>%
  na.omit() %>%
  arrange(factor(AllocatedTreatment, levels= c('Placebo', 'Levomenthol'))) %>%
  column_to_rownames(., var = 'AllocatedTreatment')

responder_matrix <- as.matrix(responder_table)

# The difference of proportions test 

prop.test(responder_matrix, correct = FALSE)

```



## Tables and figures

```{r include=TRUE, message = FALSE, warning = FALSE}

# Table with improver/non-improver counts

transpose <- t(responder_matrix)

kable(transpose) %>% 
  kable_styling(bootstrap_options = 'hover', 
                html_font = 'helvetica',
                font_size = '16',
                full_width = FALSE)


# Mosaic plot

basic_information_adapted <- basic_information %>%
  mutate(Improver_status_week6 = fct_relevel(Improver_status_week6, 'Non-improver', 'Improver'),
         AllocatedTreatment = factor(AllocatedTreatment, levels= c('Placebo', 'Levomenthol')))

mosaic_plot <- ggplot(data = basic_information_adapted) +
geom_mosaic(aes(x = product(AllocatedTreatment), fill = Improver_status_week6), na.rm=TRUE) +
labs(fill = 'Improver status at week 6') +
  scale_fill_manual(
    values = c('#D95F02','#1B9E77'), # Colours chosen from the colourblind friendly palette RColorBrewer::brewer.pal(8, 'Dark2')
    guide = guide_legend(reverse = TRUE)) + 
  theme_classic() +
    theme(legend.title = element_text(size = 12),
          axis.title.x = element_blank(),
          axis.title.y = element_blank(),
          axis.text.x = element_text(size = 11.5, colour = 'black'),  
          axis.text.y = element_text(size = 11.5, colour = 'black'),
          legend.text = element_text(size = 11.5, colour = 'black')  
          ) 

mosaic_plot 

ggsave(filename="mosaic_plot_primary_outcome.png", plot= mosaic_plot, device="png", path='<path>', height=3.75, width=6.5, units="in", dpi = 700)


```

